services:
  db:
    image: postgres:latest
    container_name: chirpnest_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: chirpnest
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./src/main/resources/db/migrations:/docker-entrypoint-initdb.d

volumes:
  db_data:
